### PR TITLE
Feature/sandbox str for jp region

### PR DESCRIPTION
**Pull request by Samemura**
Since I started to develop web site to use login and pay with amazon with Ruby On Rails, I could not connect to profile API endpoint of sandbox for jp region.

End point : https://api-sandbox.amazon.co.jp/
This SDK makes it as: https://api.sandbox.amazon.co.jp/

I corrected locally then this works fine. So I would like to merge to your base.

Note: Test environment looks lacked so I tried to prepare and now it can be run with failed.
      I am not sure this test originally passed so I did not check deeply its failed.

### CODE REVIEW

**Comment by islandskater43** [comment]
The JP sandbox endpoint issue was resolved a couple days ago via this issue:

https://github.com/amzn/login-and-pay-with-amazon-sdk-php/issues/31

There was a missing CNAME record to point api.sandbox to api-sandbox.

**Comment by pyama86** [comment]
cname might have increased again

```
% dig api.sandbox.amazon.co.jp +short
not found
```

Moreover likely to fail ssl certificate in verification..

@islandskater43

**Comment by islandskater43** [comment]
Thanks @pyama86 - we identified that this actually wasn't resolved externally, and are working to fix both the resolution AND the SSL validation. Will close this issue when resolved. I've also reopened the issue here:
https://github.com/amzn/login-and-pay-with-amazon-sdk-php/issues/31

**Comment by jordan-brough** [comment]
@islandskater43 can this be closed now?

**Comment by Samemura** [comment]
@jordan-brough
thank you. With dig, it works to me.
In similar case, some environmental varialble is nice to override this endpoint i think.
if you agree , i will changemy pr as it. otherwise just close this pr.

**Pull request closed without merging**
